config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # These get a really path helper name if declared as part of the garden resource above
  # Also have to be declared first or the route will point to gardens#show
  get  "uu-gardening-team/new_report", :to => "garden_reports#new", as: "new_garden_report"
  post "uu-gardening-team/new_report", :to => "garden_reports#create", as: "post_garden_report"

  resources :gardens, path: "uu-gardening-team" do
    resources :garden_reports, path: "reports", except: [:new, :create, :index]
  end
  resources :parents_resources, path: "uu-parents-resources", except: [:destroy]
  resources :signup_lists, path: "uu-hacktivists", only: [:index, :create]

  root 'root#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :reports, class_name: "GardenReport", foreign_key: "garden_id"

  scope :ordered_with_reports_desc, -> { order(:name).includes(:reports).order('garden_reports.created_at desc') }
end

app/models/garden_report.rb
class GardenReport < ApplicationRecord
  belongs_to :garden
  mount_uploader :photo, ReportPhotoUploader

  validates :notes, presence: true
end

app/models/parents_resource.rb
class ParentsResource < ApplicationRecord
  validates :title, presence: true
end

app/models/signup_list.rb
class SignupList < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, format: { with: /.+@.+\..+/, message: "must contain an @ and a ." }, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def set_navbar(name)
    @navbar = name
  end
end

app/controllers/garden_reports_controller.rb
class GardenReportsController < ApplicationController
  before_action { set_navbar("garden") }
  before_action :authenticate_user!, except: [:show]

  def show
    @report = GardenReport.includes(:garden).find(params[:id])
  end

  def new
    @report = GardenReport.new
    @gardens = Garden.all
  end

  def edit
    @report = GardenReport.includes(:garden).find(params[:id])
    @gardens = Garden.all
  end

  def create
    @report = GardenReport.new(garden_report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to [@report.garden, @report], notice: 'Garden report was successfully created.' }
      else
        @gardens = Garden.all
        format.html { render :new }
      end
    end
  end

  def update
    @report = GardenReport.includes(:garden).find(params[:id])

    respond_to do |format|
      if @report.update(garden_report_params)
        format.html { redirect_to garden_garden_report_path([@report.garden, @report]), notice: 'Garden report was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @report = GardenReport.find(params[:id])
    @report.destroy
    respond_to do |format|
      format.html { redirect_to @report.garden, notice: 'Garden report was successfully destroyed.' }
    end
  end

  private

  def garden_report_params
    params.require(:garden_report).permit(:notes, :photo, :remove_photo, :garden_id, :photo_cache).merge(params.permit(:garden_id))
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action { set_navbar("garden") }
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_garden, only: [:edit, :update, :destroy]

  def index
    if(params[:view_list])
      @gardens = Garden.ordered_with_reports_desc.all
      render("gardens/index_list")
    else
      @garden_reports = GardenReport.order(:created_at => :desc)
      render("gardens/index_photos")
    end
  end

  def show
    @garden = Garden.ordered_with_reports_desc.find(params[:id])
  end

  def new
    @garden = Garden.new
  end

  def edit
  end

  def create
    @garden = Garden.new(garden_params)

    respond_to do |format|
      if @garden.save
        format.html { redirect_to @garden, notice: 'Garden was successfully created.' }
        format.json { render :show, status: :created, location: @garden }
      else
        format.html { render :new }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @garden.update(garden_params)
        format.html { redirect_to @garden, notice: 'Garden was successfully updated.' }
        format.json { render :show, status: :ok, location: @garden }
      else
        format.html { render :edit }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @garden.destroy
    respond_to do |format|
      format.html { redirect_to gardens_url, notice: 'Garden was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_garden
    @garden = Garden.find(params[:id])
  end

  def garden_params
    params.require(:garden).permit(:name, :location, :description)
  end
end

app/controllers/parents_resources_controller.rb
class ParentsResourcesController < ApplicationController
  before_action { set_navbar("parents_resource") }
  before_action :set_parents_resource, only: [:show, :edit, :update, :destroy]
  before_action :categories, :age_range

  def index
    @parents_resources = ParentsResource.all
  end

  def show
  end

  def new
    @parents_resource = ParentsResource.new
  end

  def edit
  end

  def create
    @parents_resource = ParentsResource.new(parents_resource_params)

    respond_to do |format|
      if @parents_resource.save
        format.html { redirect_to @parents_resource, notice: 'Parents resource was successfully created.' }
        format.json { render :show, status: :created, location: @parents_resource }
      else
        format.html { render :new }
        format.json { render json: @parents_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @parents_resource.update(parents_resource_params)
        format.html { redirect_to @parents_resource, notice: 'Parents resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @parents_resource }
      else
        format.html { render :edit }
        format.json { render json: @parents_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_parents_resource
      @parents_resource = ParentsResource.find(params[:id])
    end

    def parents_resource_params
      min, max = params[:parents_resource][:age_range].split(',').map(&:to_i)
      age_min = age_range[min]
      age_max = age_range[max]
      params.require(:parents_resource).permit(:title, :link, :notes, :category, :price).merge({age_min: age_min, age_max: age_max})
    end

    def categories
      @categories ||= %w(Books Classes Website Video Services Other)
    end

    def age_range
      @age_range ||= ['Pre-Pregnancy', '1st Trimester', '2nd Trimester', '3rd Trimester', 'Birth', '1st Week', '1 Month', '3 Months', '6 Months', '9 Months', '1 Year', 'Toddler', 'Child', 'Preteen', 'Teen']
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/controllers/signup_lists_controller.rb
class SignupListsController < ApplicationController
  before_action { set_navbar("hacktivists") }

  def index
    @signup_list = SignupList.new
    @count = SignupList.count
  end

  def create
    @signup_list = SignupList.new(signup_list_params)

    if @signup_list.save
      SignupMailer.welcome_email(@signup_list).deliver_later
      render :json => { count: SignupList.count, message: "Thank you for joining, #{@signup_list.name}." }
    else
      render :json => { error_message: @signup_list.errors.full_messages.join(". ").concat(".") }
    end
  end

  private
  def signup_list_params
    params.require(:signup_list).permit(:name, :email)
  end
end

app/views/garden_reports/_form.html.erb
<%= form_with(model: report, url: url, method: method, html: { multipart: true }, local: true) do |f| %>
  <%= content_tag(:div, class: f.object.errors[:garden].present? ? "form-group has-error" : "form-group") do %>
    <%= f.label :garden %>
    <%= f.select :garden_id, options_from_collection_for_select(gardens, "id", "name", f.object.garden && f.object.garden.id), { prompt: "Please select a garden"}, { class: "form-control" } %>
    <%= render "shared/error_messages", label: "garden", errors: f.object.errors[:garden] %>
  <% end %>

  <%= render "shared/text_area", form: f, label: "notes" %>

  <%= content_tag(:div, class: f.object.errors[:photo].present? ? "form-group has-error" : "form-group") do %>
    <%= f.label :photo %>
    <%= f.file_field :photo, class: "form-control", id: "photo-input", accept: ".jpg,.jpeg,.gif,.png" %>
    <%= f.hidden_field :photo_cache %>
    <% if(f.object.errors[:photo].present?) %>
      <span class="help-block"><%= "Photo must be either a *.jpg, *.jpeg, *.gif, or *.png." %></span>
    <% end %>
  <% end %>

  <div class="form-group" id="preview-image-container">
    <%= image_tag(f.object.photo_url, class: "preview-image") if f.object.photo? %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

<script>
$("#photo-input").change(function(){
  displayPreviewImage(this, '#preview-image-container', '.preview-image');
});
<% if(report.photo?) %>
  $(resizeGardenPhotos.bind(this, '#preview-image-container',".preview-image"));
  $(window).resize(resizeGardenPhotos.bind(this, '#preview-image-container',".preview-image"));
<% end %>
</script>

app/views/garden_reports/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Editing Garden Report</h1>
  </div>

  <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
    <%= render 'form', report: @report, gardens: @gardens, url: [@report.garden, @report], method: "PUT" %>

    <%= link_to 'Show', [@report.garden, @report] %> |
    <%= link_to 'Garden', @report.garden %>
  </div>
</div>

app/views/garden_reports/index.html.erb
<h1>Garden Reports</h1>

<table>
  <thead>
    <tr>
      <th>Notes</th>
      <th>Garden</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @garden_reports.each do |report| %>
      <tr>
        <td><%= report.notes %></td>
        <td><%= report.garden.name %></td>
        <td><%= link_to 'Show', [report.garden,report] %></td>
        <td><%= link_to 'Edit', [:edit, report.garden,report] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garden Report', new_garden_garden_report_path(@garden) %>

app/views/garden_reports/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>New Garden Report</h1>
  </div>

  <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
    <%= render 'form', report: @report, gardens: @gardens, url: new_garden_report_path, method: "POST" %>
  </div>
</div>

app/views/garden_reports/show.html.erb
<div class="row">
  <div class="col-xs-12 col-md-6">
    <%= image_tag @report.photo.url, class: "img-responsive" %>
  </div>
  <div class="col-xs-12 col-md-6">
    <h2><%= @report.garden.name %> Report</h2>
    <p><%= @report.created_at.to_date %></p>
    <p><%= @report.notes %></p>
    <p><small><%= link_to("edit report", [:edit, @report.garden, @report]) %> | <%= link_to("view garden", @report.garden) %></small></p>
  </div>
</div>
</div>

app/views/gardens/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
    <%= form_with(model: garden, local: true) do |f| %>

      <%= render "shared/text_field", form: f, label: "name" %>
      <%= render "shared/text_field", form: f, label: "location" %>
      <%= render "shared/text_field", form: f, label: "description" %>


      <div class="form-group">
        <%= f.submit class: "btn btn-default" %>
      </div>
    <% end %>
  </div>
</div>

app/views/gardens/_garden_info.html.erb
<h2 class="bottom-margin-0"><%= garden.name %></h2>
<p><small><%= link_to "map", "https://www.google.com/maps/place/#{garden.location}", :target => :_blank %> | <%= link_to "view", garden %> | <%= link_to "edit", [:edit, garden] %></small></p>
<%= content_tag :p, garden.description %>
<h6>All Reports:</h6>
<% garden.reports.each do |report| %>
  <div class="row bottom-margin-10">
    <div class="col-xs-4">
      <%= image_tag report.photo.url, class: "img-responsive" %>
    </div>
    <div class="col-xs-8">
      <p><%= report.created_at.to_date %></p>
      <p><%= report.notes %></p>
      <p><small><%= link_to("view report", [garden, report]) %> | <%= link_to("edit report", [:edit, garden, report]) %></small></p>
    </div>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index_list.html.erb
<div class="row">
  <div class="col-xs-12 text-right">
    <p class="no-margin">( <%= link_to "view photos", gardens_path %> | <strong>view list</strong> )</p>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-10 col-md-6 col-lg-5">
    <% @gardens.each do |garden| %>
      <%= render("garden_info", garden: garden) %>
    <% end %>
  </div>
</div>

app/views/gardens/index_photos.html.erb
<div class="row">
  <div class="col-xs-12 text-right">
    <p class="no-margin">( <strong>view photos</strong> | <%= link_to "view list", gardens_path(view_list: true) %> )</p>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 text-center" id="garden-report-container">
    <% @garden_reports.each do |report| %>
      <div class="garden-report">
        <%= link_to [report.garden, report] do %>
          <%= image_tag report.photo.url, class: "auto-width-photo", data: { checkwidth: true } %>
          <p class="garden-report-text text-left">
            <span><%= report.garden.name %></span>
            <span class="pull-right"><%= report.created_at.to_date %></span>
          </p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<script>
$(resizeGardenPhotos.bind(this, '#garden-report-container', '.garden-report img'));
$(window).resize(resizeGardenPhotos.bind(this, '#garden-report-container', '.garden-report img'));
</script>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

app/views/gardens/show.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-10 col-md-6 col-lg-5">
    <%= render("garden_info", garden: @garden) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectjorgeUu</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs-3.3.7/dt-1.10.15/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/dt-1.10.15/datatables.min.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container-fluid">
      <%= render "shared/notice" %>
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/parents_resources/_form.html.erb
<%= form_with(model: parents_resource, local: true) do |f| %>
  <%= render "shared/text_field", form: f, label: "title" %>
  <%= render "shared/text_field", form: f, label: "link" %>
  <%= render "shared/text_area", form: f, label: "notes" %>
  <%= render "shared/slider_input", form: f, label: "age_range", range: @age_range %>

  <%= content_tag(:div, class: f.object.errors[:garden].present? ? "form-group has-error" : "form-group") do %>
    <%= f.label :category %>
    <%= f.select :category, options_for_select(categories, f.object.category), {}, { class: "form-control" } %>
    <%= render "shared/error_messages", label: "garden", errors: f.object.errors[:garden] %>
  <% end %>

  <%= render "shared/currency_field", form: f, label: "price" %>

  <div class="actions">
    <%= f.submit "Save Resource", class: "btn btn-default" %>
  </div>
<% end %>

app/views/parents_resources/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Edit <%= @parents_resource.title %></h1>
  </div>

  <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
    <%= render 'form', parents_resource: @parents_resource, categories: @categories %>
  </div>

  <div class="col-xs-12">
    <%= link_to 'Show', @parents_resource %> |
    <%= link_to 'Back', parents_resources_path %>
  </div>
</div>

app/views/parents_resources/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Parent's Resources</h1>
  </div>

  <div class="col-xs-12">
    <table id='parents-resources-table' class='table'>
      <thead>
        <tr>
          <th>Title</th>
          <th>Link</th>
          <th>Notes</th>
          <th>Min Age</th>
          <th>Max Age</th>
          <th>Category</th>
          <th>Price</th>
          <th colspan="1"></th>
        </tr>
      </thead>

      <tbody>
        <% @parents_resources.each do |parents_resource| %>
          <tr>
            <td><%= parents_resource.title %></td>
            <td><%= link_to parents_resource.link, parents_resource.link %></td>
            <td><%= parents_resource.notes %></td>
            <td><%= parents_resource.age_min %></td>
            <td><%= parents_resource.age_max %></td>
            <td><%= parents_resource.category %></td>
            <td><%= number_to_currency parents_resource.price %></td>
            <td><%= link_to 'Edit', edit_parents_resource_path(parents_resource) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="col-xs-12">
    <%= link_to 'New Parents Resource', new_parents_resource_path %>
  </div>
</div>

<script>
$(document).ready(function() {
      $('#parents-resources-table').DataTable();
} );
</script>

app/views/parents_resources/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Add New Resource for the Parent's Group</h1>
  </div>

  <div class="col-xs-12 col-sm-10 col-md-8 col-lg-6">
    <%= render 'form', parents_resource: @parents_resource, categories: @categories %>
  </div>

  <div class="col-xs-12">
    <%= link_to 'Back', parents_resources_path %>
  </div>
</div>

app/views/parents_resources/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <p>
    <strong>Title:</strong>
    <%= @parents_resource.title %>
    </p>

    <p>
    <strong>Link:</strong>
    <%= link_to @parents_resource.link %>
    </p>

    <p>
    <strong>Notes:</strong>
    <%= @parents_resource.notes %>
    </p>

    <p>
    <strong>Age min:</strong>
    <%= @parents_resource.age_min %>
    </p>

    <p>
    <strong>Age max:</strong>
    <%= @parents_resource.age_max %>
    </p>

    <p>
    <strong>Category:</strong>
    <%= @parents_resource.category %>
    </p>

    <p>
    <strong>Price:</strong>
    <%= number_to_currency @parents_resource.price %>
    </p>
  </div>

  <div class="col-xs-12">
    <%= link_to 'Edit', edit_parents_resource_path(@parents_resource) %> |
    <%= link_to 'Back', parents_resources_path %>
  </div>
</div>

app/views/root/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Welcome to Project Jorge</h1>
    <p>A 30 year project to end poverty and protect the environment in Houston.</p>
    <h2>Our Missions</h2>
    <ul>
      <li><%= link_to("First UU Garden Team", gardens_path) %></li>
      <li><%= link_to("First UU Parent's Resources", parents_resources_path) %></li>
      <li><%= link_to("First UU Hacktivists", signup_lists_path) %></li>
    </ul>
  </div>
</div>

app/views/shared/_currency_field.html.erb
<%= content_tag(:div, class: form.object.errors[label].present? ? "form-group has-error" : "form-group") do %>
  <%= form.label label, class: "control-label" %>
  <div class="input-group">
    <span class="input-group-addon">$</span>
    <%= form.number_field label, class: "form-control", step: "0.01", min: "0.00" %>
    <%= render "shared/error_messages", label: label, errors: form.object.errors[label] %>
  </div>
<% end %>

app/views/shared/_email_field.html.erb
<%= content_tag(:div, class: form.object.errors[label].present? ? "form-group has-error" : "form-group") do %>
  <%= form.label label %>
  <%= form.email_field label, class: "form-control" %>
  <%= render "shared/error_messages", label: label, errors: form.object.errors[label] %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if(errors.present?) %>
  <span class="help-block"><%= "#{label.capitalize} #{errors.join(", ")}." %></span>
<% end %>

app/views/shared/_footer.html.erb
<div class="container-fluid">
  <hr>
  <div class="row">
    <div class="col-xs-12">
      <p><%= link_to "Project Jorge Home", root_path %> | <%= link_to "First UU Gardening Team", gardens_path %> | <%= link_to "First UU Parent's Resources", parents_resources_path %> | <%= link_to("First UU Hacktivists", signup_lists_path) %></p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% case @navbar %>
<% when "garden" %>
  <%= render "shared/top_navbar", mission_name: "UU Gardening Team", mission_path: gardens_path do %>
    <li><%= link_to "Home", gardens_path %></li>
    <li><%= link_to "New Report", new_garden_report_path %></li>
    <li><%= link_to "New Garden", new_garden_path %></li>
    <li><%= link_to "Invite Gardener", new_user_invitation_path %></li>
  <% end %>
<% when "parents_resource" %>
  <%= render "shared/top_navbar", mission_name: "UU Parent's Resources", mission_path: gardens_path do %>
    <li><%= link_to "Home", parents_resources_path %></li>
    <li><%= link_to "New Resource", new_parents_resource_path %></li>
  <% end %>
<% when "hacktivists" %>
  <%= render "shared/top_navbar", mission_name: "UU Hacktivists", mission_path: signup_lists_path do %>
  <% end %>
<% else %>
  <%= render "shared/top_navbar", mission_name: "Project Jorge", mission_path: root_path do %>
  <% end %>
<% end %>

app/views/shared/_notice.html.erb
<div class="row">
  <div class="col-xs-12">
    <% if notice.present? %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_slider_input.html.erb
<%= content_tag(:div, class: form.object.errors[label].present? ? "form-group has-error" : "form-group") do %>
  <%= form.label label, class: "control-label bottom-margin-10" %>
  <div class="input-group">
    <%= form.text_field label,
      class: "form-control",
      data: {
        provide: 'slider',
        slider_tooltip: 'hide',
        slider_orientation: 'vertical',
        slider_min: '0',
        slider_max: range.length.to_s,
        slider_value: [range.length / 3, range.length * 2 / 3],
        slider_ticks: (0...range.length).to_a,
        slider_ticks_labels: range,
      }
    %>
    <%= render "shared/error_messages", label: label, errors: form.object.errors[label] %>
  </div>
<% end %>

app/views/shared/_text_area.html.erb
<%= content_tag(:div, class: form.object.errors[label].present? ? "form-group has-error" : "form-group") do %>
  <%= form.label label %>
  <%= form.text_area label, class: "form-control" %>
  <%= render "shared/error_messages", label: label, errors: form.object.errors[label] %>
<% end %>

app/views/shared/_text_field.html.erb
<%= content_tag(:div, class: form.object.errors[label].present? ? "form-group has-error" : "form-group") do %>
  <%= form.label label %>
  <%= form.text_field label, class: "form-control" %>
  <%= render "shared/error_messages", label: label, errors: form.object.errors[label] %>
<% end %>

app/views/shared/_top_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to mission_name, mission_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <p class="visible-xs-block navbar-text">Welcome <strong><%= user_signed_in? ? current_user.email : "guest" %></strong>!</p>
      <ul class="nav navbar-nav">
        <%= yield %>
      </ul>
      <div class="navbar-right">
        <p class="hidden-xs navbar-text">Welcome <strong><%= user_signed_in? ? current_user.email : "guest" %></strong>!</p>
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "Logout", destroy_user_session_path, method: "DELETE" %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/signup_lists/_form.html.erb
<%= form_with(model: signup_list, local: true, id: "signup-list-form", data: { remote: true, type: :json }) do |f| %>
  <%= render "shared/text_field", form: f, label: "name" %>
  <%= render "shared/email_field", form: f, label: "email" %>

  <div class="actions">
    <%= f.submit "Join!", class: "btn btn-default", data: { disable_with: "Join!" } %>
    <%= link_to "Clear", "#", class: "pull-right", id: "clear-form" %>
  </div>
<% end %>

<script>
function successHandler (data) {
  if(data.error_message) {
    $("#message").text(data.error_message).slideDown(300);
  } else {
    $(this)[0].reset();
    if("" == $("#message").text()) {
      $("#message").text(data.message).slideDown(300, function () {
        $(this).delay(3000).slideUp(300, function() {
          $(this).text("");
          $("#count").fadeOut(300, function() {
            $(this).text(data.count).fadeIn(300);
          });
        });
      });
    } else {
      $("#message").fadeOut(300, function () {
        $(this).text(data.message).fadeIn(300, function () {
          $(this).delay(3000).slideUp(300, function() {
            $(this).text("");
            $("#count").fadeOut(300, function() {
              $(this).text(data.count).fadeIn(300);
            });
          });
        });
      });
    }
  }
}

function errorHandler (e, a,data) {
  console.log(data);
  $("#message").text("Something went wrong. :/").slideDown(300);
}

$(document).ready(function() {
  $("#clear-form").on("click", function () {
    $("form#signup-list-form")[0].reset();
    $("#message").slideUp(300, function() {
      $(this).text("");
    });
  });
  $("form#signup-list-form").submit(function(e) {
    e.preventDefault();
    $.ajax({
      url: $(this).attr('action'),
      type: $(this).attr('method'),
      dataType: 'json',
      data: $(this).serialize(),
      success: successHandler.bind(this),
      error: errorHandler.bind(this)
    });
  });
});
</script>

app/views/signup_lists/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Join the UU Hacktivists' Mailing List</h1>
    <p><span id="count"><%= @count %></span> members have signed up.</p>
    <p style="display: none;" id="message"></p>

  </div>
  <div class="col-xs-12 col-md-8 col-lg-6">
    <%= render 'form', signup_list: @signup_list %>
  </div>
</div>